spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/voting_app
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8282