package com.example.demo.config;

import java.io.UnsupportedEncodingException;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.example.demo.service.EmailOtpService;

import jakarta.mail.MessagingException;

@Service
public class OtpEmailTemplate {

	@Autowired
	private EmailOtpService emailOtpService;
	
	public void sendOTP(String email,String otp) {
		String Head ="Otp verfication";
		String mailContentOtp ="<!DOCTYPE html>\r\n"
				+ "<html>\r\n"
				+ "\r\n"
				+ "<head>\r\n"
				+ "    <title></title>\r\n"
				+ "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n"
				+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
				+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n"
				+ "    <style type=\"text/css\">\r\n"
				+ "        @media screen {\r\n"
				+ "            @font-face {\r\n"
				+ "                font-family: 'Lato';\r\n"
				+ "                font-style: normal;\r\n"
				+ "                font-weight: 400;\r\n"
				+ "                src: local('Lato Regular'), local('Lato-Regular'), url(https://fonts.gstatic.com/s/lato/v11/qIIYRU-oROkIk8vfvxw6QvesZW2xOQ-xsNqO47m55DA.woff) format('woff');\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "            @font-face {\r\n"
				+ "                font-family: 'Lato';\r\n"
				+ "                font-style: normal;\r\n"
				+ "                font-weight: 700;\r\n"
				+ "                src: local('Lato Bold'), local('Lato-Bold'), url(https://fonts.gstatic.com/s/lato/v11/qdgUG4U09HnJwhYI-uK18wLUuEpTyoUstqEm5AMlJo4.woff) format('woff');\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "            @font-face {\r\n"
				+ "                font-family: 'Lato';\r\n"
				+ "                font-style: italic;\r\n"
				+ "                font-weight: 400;\r\n"
				+ "                src: local('Lato Italic'), local('Lato-Italic'), url(https://fonts.gstatic.com/s/lato/v11/RYyZNoeFgb0l7W3Vu1aSWOvvDin1pK8aKteLpeZ5c0A.woff) format('woff');\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "            @font-face {\r\n"
				+ "                font-family: 'Lato';\r\n"
				+ "                font-style: italic;\r\n"
				+ "                font-weight: 700;\r\n"
				+ "                src: local('Lato Bold Italic'), local('Lato-BoldItalic'), url(https://fonts.gstatic.com/s/lato/v11/HkF_qI1x_noxlxhrhMQYELO3LdcAZYWl9Si6vvxL-qU.woff) format('woff');\r\n"
				+ "            }\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        /* CLIENT-SPECIFIC STYLES */\r\n"
				+ "        body,\r\n"
				+ "        table,\r\n"
				+ "        td,\r\n"
				+ "        a {\r\n"
				+ "            -webkit-text-size-adjust: 100%;\r\n"
				+ "            -ms-text-size-adjust: 100%;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        table,\r\n"
				+ "        td {\r\n"
				+ "            mso-table-lspace: 0pt;\r\n"
				+ "            mso-table-rspace: 0pt;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        img {\r\n"
				+ "            -ms-interpolation-mode: bicubic;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        /* RESET STYLES */\r\n"
				+ "        img {\r\n"
				+ "            border: 0;\r\n"
				+ "            height: auto;\r\n"
				+ "            line-height: 100%;\r\n"
				+ "            outline: none;\r\n"
				+ "            text-decoration: none;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        table {\r\n"
				+ "            border-collapse: collapse !important;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        body {\r\n"
				+ "            height: 100% !important;\r\n"
				+ "            margin: 0 !important;\r\n"
				+ "            padding: 0 !important;\r\n"
				+ "            width: 100% !important;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        /* iOS BLUE LINKS */\r\n"
				+ "        a[x-apple-data-detectors] {\r\n"
				+ "            color: inherit !important;\r\n"
				+ "            text-decoration: none !important;\r\n"
				+ "            font-size: inherit !important;\r\n"
				+ "            font-family: inherit !important;\r\n"
				+ "            font-weight: inherit !important;\r\n"
				+ "            line-height: inherit !important;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        /* MOBILE STYLES */\r\n"
				+ "        @media screen and (max-width:600px) {\r\n"
				+ "            h1 {\r\n"
				+ "                font-size: 32px !important;\r\n"
				+ "                line-height: 32px !important;\r\n"
				+ "            }\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        /* ANDROID CENTER FIX */\r\n"
				+ "        div[style*=\"margin: 16px 0;\"] {\r\n"
				+ "            margin: 0 !important;\r\n"
				+ "        }\r\n"
				+ "    </style>\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body style=\"background-color: #f4f4f4; margin: 0 !important; padding: 0 !important;\">\r\n"
				+ "    <!-- HIDDEN PREHEADER TEXT -->\r\n"
				+ "    <div style=\"display: none; font-size: 1px; color: #fefefe; line-height: 1px; font-family: 'Lato', Helvetica, Arial, sans-serif; max-height: 0px; max-width: 0px; opacity: 0; overflow: hidden;\"> We're thrilled to have you here! Get ready to dive into your new account.\r\n"
				+ "    </div>\r\n"
				+ "    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
				+ "        <!-- LOGO -->\r\n"
				+ "        <tr>\r\n"
				+ "            <td bgcolor=\"#FFA73B\" align=\"center\">\r\n"
				+ "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"max-width: 600px;\">\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td align=\"center\" valign=\"top\" style=\"padding: 40px 10px 40px 10px;\"> </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                </table>\r\n"
				+ "            </td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td bgcolor=\"#FFA73B\" align=\"center\" style=\"padding: 0px 10px 0px 10px;\">\r\n"
				+ "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"max-width: 600px;\">\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td bgcolor=\"#ffffff\" align=\"center\" valign=\"top\" style=\"padding: 40px 20px 20px 20px; border-radius: 4px 4px 0px 0px; color: #111111; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 48px; font-weight: 400; letter-spacing: 4px; line-height: 48px;\">\r\n"
				+ "                            <h1 style=\"font-size: 48px; font-weight: 400; margin: 2;\">Welcome!</h1> <img src=\" https://img.icons8.com/clouds/100/000000/handshake.png\" width=\"125\" height=\"120\" style=\"display: block; border: 0px;\" />\r\n"
				+ "                        </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                </table>\r\n"
				+ "            </td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td bgcolor=\"#f4f4f4\" align=\"center\" style=\"padding: 0px 10px 0px 10px;\">\r\n"
				+ "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"max-width: 600px;\">\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td bgcolor=\"#ffffff\" align=\"left\" style=\"padding: 20px 30px 40px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;\">\r\n"
				+ "                            <p style=\"margin: 0;\">We're excited to have you get started. First, you need to confirm your account. Just press the button below.</p>\r\n"
				+ "                        </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td bgcolor=\"#ffffff\" align=\"left\">\r\n"
				+ "                            <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
				+ "                                <tr>\r\n"
				+ "                                    <td bgcolor=\"#ffffff\" align=\"center\" style=\"padding: 20px 30px 60px 30px;\">\r\n"
				+ "                                        <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
				+ "                                            <tr>\r\n"
				+ "                                                <td align=\"center\" style=\"border-radius: 3px;\" bgcolor=\"#FFA73B\"><a href=\"#\" target=\"_blank\" style=\"font-size: 20px; font-family: Helvetica, Arial, sans-serif; color: #ffffff; text-decoration: none; color: #ffffff; text-decoration: none; padding: 15px 25px; border-radius: 2px; border: 1px solid #FFA73B; display: inline-block;\">"+otp+"</a></td>\r\n"
				+ "                                            </tr>\r\n"
				+ "                                        </table>\r\n"
				+ "                                    </td>\r\n"
				+ "                                </tr>\r\n"
				+ "                            </table>\r\n"
				+ "                        </td>\r\n"
				+ "                    </tr> <!-- COPY -->\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td bgcolor=\"#ffffff\" align=\"left\" style=\"padding: 0px 30px 0px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;\">\r\n"
				+ "                            <p style=\"margin: 0;\">If that doesn't work, copy and paste the following link in your browser:</p>\r\n"
				+ "                        </td>\r\n"
				+ "                    </tr> <!-- COPY -->\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td bgcolor=\"#ffffff\" align=\"left\" style=\"padding: 20px 30px 20px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;\">\r\n"
				+ "                            <p style=\"margin: 0;\"><a href=\"#\" target=\"_blank\" style=\"color: #FFA73B;\">https://bit.li.utlddssdstueincx</a></p>\r\n"
				+ "                        </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td bgcolor=\"#ffffff\" align=\"left\" style=\"padding: 0px 30px 20px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;\">\r\n"
				+ "                            <p style=\"margin: 0;\">If you have any questions, just reply to this email&mdash;we're always happy to help out.</p>\r\n"
				+ "                        </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td bgcolor=\"#ffffff\" align=\"left\" style=\"padding: 0px 30px 40px 30px; border-radius: 0px 0px 4px 4px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;\">\r\n"
				+ "                            <p style=\"margin: 0;\">Cheers,<br>BBB Team</p>\r\n"
				+ "                        </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                </table>\r\n"
				+ "            </td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td bgcolor=\"#f4f4f4\" align=\"center\" style=\"padding: 30px 10px 0px 10px;\">\r\n"
				+ "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"max-width: 600px;\">\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td bgcolor=\"#FFECD1\" align=\"center\" style=\"padding: 30px 30px 30px 30px; border-radius: 4px 4px 4px 4px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;\">\r\n"
				+ "                            <h2 style=\"font-size: 20px; font-weight: 400; color: #111111; margin: 0;\">Need more help?</h2>\r\n"
				+ "                            <p style=\"margin: 0;\"><a href=\"#\" target=\"_blank\" style=\"color: #FFA73B;\">We&rsquo;re here to help you out</a></p>\r\n"
				+ "                        </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                </table>\r\n"
				+ "            </td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td bgcolor=\"#f4f4f4\" align=\"center\" style=\"padding: 0px 10px 0px 10px;\">\r\n"
				+ "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"max-width: 600px;\">\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td bgcolor=\"#f4f4f4\" align=\"left\" style=\"padding: 0px 30px 30px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; line-height: 18px;\"> <br>\r\n"
				+ "                            <p style=\"margin: 0;\">If these emails get annoying, please feel free to <a href=\"#\" target=\"_blank\" style=\"color: #111111; font-weight: 700;\">unsubscribe</a>.</p>\r\n"
				+ "                        </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                </table>\r\n"
				+ "            </td>\r\n"
				+ "        </tr>\r\n"
				+ "    </table>\r\n"
				+ "</body>\r\n"
				+ "\r\n"
				+ "</html>";
		try {
			emailOtpService.sendMail(Head, email, mailContentOtp);
		} catch (UnsupportedEncodingException | MessagingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		}
		
		public void AfterRegisterUser(String email,String Username) {
//			System.out.println(email+"$$$$$$$$$$"+Username);
			String Head ="Registration Successful: Welcome to [VotingBhart] Account is Ready ✨";
			String mailContentOtp ="<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
					+ "<html dir=\"ltr\" xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\r\n"
					+ "\r\n"
					+ "<head>\r\n"
					+ "    <meta charset=\"UTF-8\">\r\n"
					+ "    <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\">\r\n"
					+ "    <meta name=\"x-apple-disable-message-reformatting\">\r\n"
					+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
					+ "    <meta content=\"telephone=no\" name=\"format-detection\">\r\n"
					+ "    <title></title>\r\n"
					+ "    <!--[if (mso 16)]>\r\n"
					+ "    <style type=\"text/css\">\r\n"
					+ "    a {text-decoration: none;}\r\n"
					+ "    </style>\r\n"
					+ "    <![endif]-->\r\n"
					+ "    <!--[if gte mso 9]><style>sup { font-size: 100% !important; }</style><![endif]-->\r\n"
					+ "    <!--[if gte mso 9]>\r\n"
					+ "<xml>\r\n"
					+ "    <o:OfficeDocumentSettings>\r\n"
					+ "    <o:AllowPNG></o:AllowPNG>\r\n"
					+ "    <o:PixelsPerInch>96</o:PixelsPerInch>\r\n"
					+ "    </o:OfficeDocumentSettings>\r\n"
					+ "</xml>\r\n"
					+ "<![endif]-->\r\n"
					+ "    <!--[if !mso]><!-- -->\r\n"
					+ "    <link href=\"https://fonts.googleapis.com/css2?family=Imprima&display=swap\" rel=\"stylesheet\">\r\n"
					+ "    <!--<![endif]-->\r\n"
					+ "</head>\r\n"
					+ "\r\n"
					+ "<body>\r\n"
					+ "    <div dir=\"ltr\" class=\"es-wrapper-color\">\r\n"
					+ "        <!--[if gte mso 9]>\r\n"
					+ "			<v:background xmlns:v=\"urn:schemas-microsoft-com:vml\" fill=\"t\">\r\n"
					+ "				<v:fill type=\"tile\" color=\"#ffffff\"></v:fill>\r\n"
					+ "			</v:background>\r\n"
					+ "		<![endif]-->\r\n"
					+ "        <table class=\"es-wrapper\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
					+ "            <tbody>\r\n"
					+ "                <tr>\r\n"
					+ "                    <td class=\"esd-email-paddings\" valign=\"top\">\r\n"
					+ "                        <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-footer esd-header-popover\" align=\"center\">\r\n"
					+ "                            <tbody>\r\n"
					+ "                                <tr>\r\n"
					+ "                                    <td class=\"esd-stripe\" align=\"center\">\r\n"
					+ "                                        <table bgcolor=\"#bcb8b1\" class=\"es-footer-body\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\">\r\n"
					+ "                                            <tbody>\r\n"
					+ "                                                <tr>\r\n"
					+ "                                                    <td class=\"esd-structure es-p20t es-p20b es-p40r es-p40l\" align=\"left\">\r\n"
					+ "                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                            <tbody>\r\n"
					+ "                                                                <tr>\r\n"
					+ "                                                                    <td width=\"520\" class=\"esd-container-frame\" align=\"center\" valign=\"top\">\r\n"
					+ "                                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                                            <tbody>\r\n"
					+ "                                                                                <tr>\r\n"
					+ "                                                                                    <td align=\"center\" class=\"esd-block-image\" style=\"font-size: 0px;\"><a target=\"_blank\" href=\"https://viewstripo.email\"><img src=\"https://fcnwmia.stripocdn.email/content/guids/CABINET_055ba03e85e991c70304fecd78a2dceaf6b3f0bc1b0eb49336463d3599679494/images/vector.png\" alt=\"Logo\" style=\"display: block;\" height=\"60\" title=\"Logo\"></a></td>\r\n"
					+ "                                                                                </tr>\r\n"
					+ "                                                                            </tbody>\r\n"
					+ "                                                                        </table>\r\n"
					+ "                                                                    </td>\r\n"
					+ "                                                                </tr>\r\n"
					+ "                                                            </tbody>\r\n"
					+ "                                                        </table>\r\n"
					+ "                                                    </td>\r\n"
					+ "                                                </tr>\r\n"
					+ "                                            </tbody>\r\n"
					+ "                                        </table>\r\n"
					+ "                                    </td>\r\n"
					+ "                                </tr>\r\n"
					+ "                            </tbody>\r\n"
					+ "                        </table>\r\n"
					+ "                        <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-content\" align=\"center\">\r\n"
					+ "                            <tbody>\r\n"
					+ "                                <tr>\r\n"
					+ "                                    <td class=\"esd-stripe\" align=\"center\">\r\n"
					+ "                                        <table bgcolor=\"#efefef\" class=\"es-content-body\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" style=\"border-radius: 20px 20px 0 0 \">\r\n"
					+ "                                            <tbody>\r\n"
					+ "                                                <tr>\r\n"
					+ "                                                    <td class=\"esd-structure es-p40t es-p40r es-p40l\" align=\"left\">\r\n"
					+ "                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                            <tbody>\r\n"
					+ "                                                                <tr>\r\n"
					+ "                                                                    <td width=\"520\" class=\"esd-container-frame\" align=\"center\" valign=\"top\">\r\n"
					+ "                                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                                            <tbody>\r\n"
					+ "                                                                                <tr>\r\n"
					+ "                                                                                    <td align=\"left\" class=\"esd-block-image\" style=\"font-size: 0px;\"><a target=\"_blank\" href=\"https://viewstripo.email\"><img src=\"https://fcnwmia.stripocdn.email/content/guids/CABINET_ee77850a5a9f3068d9355050e69c76d26d58c3ea2927fa145f0d7a894e624758/images/group_4076323.png\" alt=\"Confirm email\" style=\"display: block; border-radius: 100px;\" width=\"100\" title=\"Confirm email\" class=\"adapt-img\"></a></td>\r\n"
					+ "                                                                                </tr>\r\n"
					+ "                                                                            </tbody>\r\n"
					+ "                                                                        </table>\r\n"
					+ "                                                                    </td>\r\n"
					+ "                                                                </tr>\r\n"
					+ "                                                            </tbody>\r\n"
					+ "                                                        </table>\r\n"
					+ "                                                    </td>\r\n"
					+ "                                                </tr>\r\n"
					+ "                                                <tr>\r\n"
					+ "                                                    <td class=\"es-p20t es-p40r es-p40l esd-structure\" align=\"left\">\r\n"
					+ "                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                            <tbody>\r\n"
					+ "                                                                <tr>\r\n"
					+ "                                                                    <td width=\"520\" class=\"esd-container-frame\" align=\"center\" valign=\"top\">\r\n"
					+ "                                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" bgcolor=\"#fafafa\" style=\"background-color: #fafafa; border-radius: 10px; border-collapse: separate;\">\r\n"
					+ "                                                                            <tbody>\r\n"
					+ "                                                                                <tr>\r\n"
					+ "                                                                                    <td align=\"left\" class=\"esd-block-text es-p20\">\r\n"
					+ "                                                                                        <h3>Welcome, "+Username+"</h3>\r\n"
					+ "                                                                                        <p><br></p>\r\n"
					+ "                                                                                        <p>Congratulations on completing your registration with [VotingBhart] ! 🎉</p>\r\n"
					+ "                                                                                        <p><br></p>\r\n"
					+ "                                                                                        <p>You're now part of our community, and we're thrilled to have you on board. Get ready to explore, connect, and [state the main benefit or purpose of your platform].<br></p>\r\n"
					+ "                                                                                        <p><br></p>\r\n"
					+ "                                                                                        <p>Should you have any questions or need assistance, feel free to reach out to our friendly support team. We're here to help you make the most of your [Your Platform Name] experience.<br></p>\r\n"
					+ "                                                                                        <p><br></p>\r\n"
					+ "                                                                                        <p>Should you have any questions or need assistance, feel free to reach out to our friendly support team. We're here to help you make the most of your [Your Platform Name] experience.<br></p>\r\n"
					+ "                                                                                        <p><br></p>\r\n"
					+ "                                                                                        <p>Best regards,&nbsp;<br></p>\r\n"
					+ "                                                                                        <p>The [VotingBhart] Team<br></p>\r\n"
					+ "                                                                                    </td>\r\n"
					+ "                                                                                </tr>\r\n"
					+ "                                                                            </tbody>\r\n"
					+ "                                                                        </table>\r\n"
					+ "                                                                    </td>\r\n"
					+ "                                                                </tr>\r\n"
					+ "                                                            </tbody>\r\n"
					+ "                                                        </table>\r\n"
					+ "                                                    </td>\r\n"
					+ "                                                </tr>\r\n"
					+ "                                            </tbody>\r\n"
					+ "                                        </table>\r\n"
					+ "                                    </td>\r\n"
					+ "                                </tr>\r\n"
					+ "                            </tbody>\r\n"
					+ "                        </table>\r\n"
					+ "                        <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-content\" align=\"center\">\r\n"
					+ "                            <tbody>\r\n"
					+ "                                <tr>\r\n"
					+ "                                    <td class=\"esd-stripe\" align=\"center\">\r\n"
					+ "                                        <table bgcolor=\"#efefef\" class=\"es-content-body\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\">\r\n"
					+ "                                            <tbody>\r\n"
					+ "                                                <tr>\r\n"
					+ "                                                    <td class=\"esd-structure es-p40r es-p40l\" align=\"left\">\r\n"
					+ "                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                            <tbody>\r\n"
					+ "                                                                <tr>\r\n"
					+ "                                                                    <td width=\"520\" class=\"esd-container-frame\" align=\"center\" valign=\"top\">\r\n"
					+ "                                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                                            <tbody>\r\n"
					+ "                                                                                <tr>\r\n"
					+ "                                                                                    <td align=\"center\" class=\"esd-block-spacer es-p40t es-p20b\" style=\"font-size:0\">\r\n"
					+ "                                                                                        <table border=\"0\" width=\"100%\" height=\"100%\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
					+ "                                                                                            <tbody>\r\n"
					+ "                                                                                                <tr>\r\n"
					+ "                                                                                                    <td style=\"border-bottom: 1px solid #666666; background: unset; height: 1px; width: 100%; margin: 0px;\"></td>\r\n"
					+ "                                                                                                </tr>\r\n"
					+ "                                                                                            </tbody>\r\n"
					+ "                                                                                        </table>\r\n"
					+ "                                                                                    </td>\r\n"
					+ "                                                                                </tr>\r\n"
					+ "                                                                            </tbody>\r\n"
					+ "                                                                        </table>\r\n"
					+ "                                                                    </td>\r\n"
					+ "                                                                </tr>\r\n"
					+ "                                                            </tbody>\r\n"
					+ "                                                        </table>\r\n"
					+ "                                                    </td>\r\n"
					+ "                                                </tr>\r\n"
					+ "                                            </tbody>\r\n"
					+ "                                        </table>\r\n"
					+ "                                    </td>\r\n"
					+ "                                </tr>\r\n"
					+ "                            </tbody>\r\n"
					+ "                        </table>\r\n"
					+ "                        <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-content\" align=\"center\">\r\n"
					+ "                            <tbody>\r\n"
					+ "                                <tr>\r\n"
					+ "                                    <td class=\"esd-stripe\" align=\"center\">\r\n"
					+ "                                        <table bgcolor=\"#efefef\" class=\"es-content-body\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" style=\"border-radius: 0 0 20px 20px\">\r\n"
					+ "                                            <tbody>\r\n"
					+ "                                                <tr>\r\n"
					+ "                                                    <td class=\"esd-structure es-p20t es-p20b es-p40r es-p40l esdev-adapt-off\" align=\"left\">\r\n"
					+ "                                                        <table width=\"520\" cellpadding=\"0\" cellspacing=\"0\" class=\"esdev-mso-table\">\r\n"
					+ "                                                            <tbody>\r\n"
					+ "                                                                <tr>\r\n"
					+ "                                                                    <td class=\"esdev-mso-td\" valign=\"top\">\r\n"
					+ "                                                                        <table cellpadding=\"0\" cellspacing=\"0\" align=\"left\" class=\"es-left\">\r\n"
					+ "                                                                            <tbody>\r\n"
					+ "                                                                                <tr>\r\n"
					+ "                                                                                    <td width=\"47\" class=\"esd-container-frame\" align=\"center\" valign=\"top\">\r\n"
					+ "                                                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                                                            <tbody>\r\n"
					+ "                                                                                                <tr>\r\n"
					+ "                                                                                                    <td align=\"center\" class=\"esd-block-image es-m-txt-l\" style=\"font-size: 0px;\"><a target=\"_blank\" href=\"https://viewstripo.email\"><img src=\"https://fcnwmia.stripocdn.email/content/guids/CABINET_ee77850a5a9f3068d9355050e69c76d26d58c3ea2927fa145f0d7a894e624758/images/group_4076325.png\" alt=\"Demo\" style=\"display: block;\" width=\"47\" title=\"Demo\"></a></td>\r\n"
					+ "                                                                                                </tr>\r\n"
					+ "                                                                                            </tbody>\r\n"
					+ "                                                                                        </table>\r\n"
					+ "                                                                                    </td>\r\n"
					+ "                                                                                </tr>\r\n"
					+ "                                                                            </tbody>\r\n"
					+ "                                                                        </table>\r\n"
					+ "                                                                    </td>\r\n"
					+ "                                                                    <td width=\"20\"></td>\r\n"
					+ "                                                                    <td class=\"esdev-mso-td\" valign=\"top\">\r\n"
					+ "                                                                        <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-right\" align=\"right\">\r\n"
					+ "                                                                            <tbody>\r\n"
					+ "                                                                                <tr>\r\n"
					+ "                                                                                    <td width=\"453\" class=\"esd-container-frame\" align=\"center\" valign=\"top\">\r\n"
					+ "                                                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                                                            <tbody>\r\n"
					+ "                                                                                                <tr>\r\n"
					+ "                                                                                                    <td align=\"left\" class=\"esd-block-text\">\r\n"
					+ "                                                                                                        <p style=\"font-size: 16px;\">\"Our website's customer support team is here for you 24/7.\"<a target=\"_blank\" style=\"font-size: 16px;\" href=\"https://viewstripo.email\"></a></p>\r\n"
					+ "                                                                                                    </td>\r\n"
					+ "                                                                                                </tr>\r\n"
					+ "                                                                                            </tbody>\r\n"
					+ "                                                                                        </table>\r\n"
					+ "                                                                                    </td>\r\n"
					+ "                                                                                </tr>\r\n"
					+ "                                                                            </tbody>\r\n"
					+ "                                                                        </table>\r\n"
					+ "                                                                    </td>\r\n"
					+ "                                                                </tr>\r\n"
					+ "                                                            </tbody>\r\n"
					+ "                                                        </table>\r\n"
					+ "                                                    </td>\r\n"
					+ "                                                </tr>\r\n"
					+ "                                            </tbody>\r\n"
					+ "                                        </table>\r\n"
					+ "                                    </td>\r\n"
					+ "                                </tr>\r\n"
					+ "                            </tbody>\r\n"
					+ "                        </table>\r\n"
					+ "                        <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-footer\" align=\"center\">\r\n"
					+ "                            <tbody>\r\n"
					+ "                                <tr>\r\n"
					+ "                                    <td class=\"esd-stripe\" align=\"center\">\r\n"
					+ "                                        <table bgcolor=\"#bcb8b1\" class=\"es-footer-body\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\">\r\n"
					+ "                                            <tbody>\r\n"
					+ "                                                <tr>\r\n"
					+ "                                                    <td class=\"esd-structure es-p40t es-p30b es-p20r es-p20l\" align=\"left\" esd-custom-block-id=\"853188\">\r\n"
					+ "                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                            <tbody>\r\n"
					+ "                                                                <tr>\r\n"
					+ "                                                                    <td width=\"560\" align=\"left\" class=\"esd-container-frame\">\r\n"
					+ "                                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                                            <tbody>\r\n"
					+ "                                                                                <tr>\r\n"
					+ "                                                                                    <td align=\"center\" class=\"esd-block-social es-m-txt-c es-p10t es-p20b\" style=\"font-size:0\">\r\n"
					+ "                                                                                        <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-table-not-adapt es-social\">\r\n"
					+ "                                                                                            <tbody>\r\n"
					+ "                                                                                                <tr>\r\n"
					+ "                                                                                                    <td align=\"center\" valign=\"top\" esd-tmp-icon-type=\"twitter\" class=\"es-p5r\"><a target=\"_blank\" href><img src=\"https://fcnwmia.stripocdn.email/content/assets/img/social-icons/logo-black/twitter-logo-black.png\" alt=\"Tw\" title=\"Twitter\" height=\"24\"></a></td>\r\n"
					+ "                                                                                                    <td align=\"center\" valign=\"top\" esd-tmp-icon-type=\"facebook\" class=\"es-p5r\"><a target=\"_blank\" href><img src=\"https://fcnwmia.stripocdn.email/content/assets/img/social-icons/logo-black/facebook-logo-black.png\" alt=\"Fb\" title=\"Facebook\" height=\"24\"></a></td>\r\n"
					+ "                                                                                                    <td align=\"center\" valign=\"top\" esd-tmp-icon-type=\"linkedin\"><a target=\"_blank\" href><img src=\"https://fcnwmia.stripocdn.email/content/assets/img/social-icons/logo-black/linkedin-logo-black.png\" alt=\"In\" title=\"Linkedin\" height=\"24\"></a></td>\r\n"
					+ "                                                                                                </tr>\r\n"
					+ "                                                                                            </tbody>\r\n"
					+ "                                                                                        </table>\r\n"
					+ "                                                                                    </td>\r\n"
					+ "                                                                                </tr>\r\n"
					+ "                                                                                <tr>\r\n"
					+ "                                                                                    <td align=\"center\" class=\"esd-block-text\" esd-links-underline=\"none\">\r\n"
					+ "                                                                                        <p style=\"font-size: 13px;\"><a target=\"_blank\" style=\"text-decoration: none;\"></a><a target=\"_blank\" style=\"text-decoration: none;\">Privacy Policy</a><a target=\"_blank\" style=\"font-size: 13px; text-decoration: none;\"></a> • <a target=\"_blank\" style=\"text-decoration: none;\">Unsubscribe</a></p>\r\n"
					+ "                                                                                    </td>\r\n"
					+ "                                                                                </tr>\r\n"
					+ "                                                                                <tr>\r\n"
					+ "                                                                                    <td align=\"center\" class=\"esd-block-text es-p20t\" esd-links-underline=\"none\">\r\n"
					+ "                                                                                        <p><a target=\"_blank\"></a>Copyright © 2023 VotingBhart<a target=\"_blank\"></a></p>\r\n"
					+ "                                                                                    </td>\r\n"
					+ "                                                                                </tr>\r\n"
					+ "                                                                            </tbody>\r\n"
					+ "                                                                        </table>\r\n"
					+ "                                                                    </td>\r\n"
					+ "                                                                </tr>\r\n"
					+ "                                                            </tbody>\r\n"
					+ "                                                        </table>\r\n"
					+ "                                                    </td>\r\n"
					+ "                                                </tr>\r\n"
					+ "                                                <tr>\r\n"
					+ "                                                    <td class=\"esd-structure es-p40t es-p30b es-p20r es-p20l\" align=\"left\" esd-custom-block-id=\"853188\">\r\n"
					+ "                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                            <tbody>\r\n"
					+ "                                                                <tr>\r\n"
					+ "                                                                    <td width=\"560\" align=\"left\" class=\"esd-container-frame\">\r\n"
					+ "                                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                                            <tbody>\r\n"
					+ "                                                                                <tr>\r\n"
					+ "                                                                                    <td align=\"center\" class=\"esd-empty-container\" style=\"display: none;\"></td>\r\n"
					+ "                                                                                </tr>\r\n"
					+ "                                                                            </tbody>\r\n"
					+ "                                                                        </table>\r\n"
					+ "                                                                    </td>\r\n"
					+ "                                                                </tr>\r\n"
					+ "                                                            </tbody>\r\n"
					+ "                                                        </table>\r\n"
					+ "                                                    </td>\r\n"
					+ "                                                </tr>\r\n"
					+ "                                            </tbody>\r\n"
					+ "                                        </table>\r\n"
					+ "                                    </td>\r\n"
					+ "                                </tr>\r\n"
					+ "                            </tbody>\r\n"
					+ "                        </table>\r\n"
					+ "                        <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-footer esd-footer-popover\" align=\"center\">\r\n"
					+ "                            <tbody>\r\n"
					+ "                                <tr>\r\n"
					+ "                                    <td class=\"esd-stripe\" align=\"center\" esd-custom-block-id=\"819294\">\r\n"
					+ "                                        <table bgcolor=\"#ffffff\" class=\"es-footer-body\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\">\r\n"
					+ "                                            <tbody>\r\n"
					+ "                                                <tr>\r\n"
					+ "                                                    <td class=\"esd-structure es-p20\" align=\"left\">\r\n"
					+ "                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                            <tbody>\r\n"
					+ "                                                                <tr>\r\n"
					+ "                                                                    <td width=\"560\" class=\"esd-container-frame\" align=\"left\">\r\n"
					+ "                                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                                            <tbody>\r\n"
					+ "                                                                                <tr>\r\n"
					+ "                                                                                    <td align=\"center\" class=\"esd-empty-container\" style=\"display: none;\"></td>\r\n"
					+ "                                                                                </tr>\r\n"
					+ "                                                                            </tbody>\r\n"
					+ "                                                                        </table>\r\n"
					+ "                                                                    </td>\r\n"
					+ "                                                                </tr>\r\n"
					+ "                                                            </tbody>\r\n"
					+ "                                                        </table>\r\n"
					+ "                                                    </td>\r\n"
					+ "                                                </tr>\r\n"
					+ "                                            </tbody>\r\n"
					+ "                                        </table>\r\n"
					+ "                                    </td>\r\n"
					+ "                                </tr>\r\n"
					+ "                            </tbody>\r\n"
					+ "                        </table>\r\n"
					+ "                    </td>\r\n"
					+ "                </tr>\r\n"
					+ "            </tbody>\r\n"
					+ "        </table>\r\n"
					+ "    </div>\r\n"
					+ "</body>\r\n"
					+ "\r\n"
					+ "</html>";
			
			try {
				emailOtpService.afterRegisterEmail(Head, email, mailContentOtp);
			} catch (UnsupportedEncodingException | MessagingException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
	}
}
