package com.example.demo.config;

import java.io.UnsupportedEncodingException;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.example.demo.service.EmailOtpService;

import jakarta.mail.MessagingException;

@Service
public class OtpEmailTemplate {

	@Autowired
	private EmailOtpService emailOtpService;
	
	public void sendOTP(String email,String otp) {

		String Head ="Otp verfication";
		String mailContentOtp ="<!DOCTYPE html>\r\n"
				+ "<html>\r\n"
				+ "\r\n"
				+ "<head>\r\n"
				+ "    <title></title>\r\n"
				+ "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n"
				+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
				+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n"
				+ "    <style type=\"text/css\">\r\n"
				+ "        @media screen {\r\n"
				+ "            @font-face {\r\n"
				+ "                font-family: 'Lato';\r\n"
				+ "                font-style: normal;\r\n"
				+ "                font-weight: 400;\r\n"
				+ "                src: local('Lato Regular'), local('Lato-Regular'), url(https://fonts.gstatic.com/s/lato/v11/qIIYRU-oROkIk8vfvxw6QvesZW2xOQ-xsNqO47m55DA.woff) format('woff');\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "            @font-face {\r\n"
				+ "                font-family: 'Lato';\r\n"
				+ "                font-style: normal;\r\n"
				+ "                font-weight: 700;\r\n"
				+ "                src: local('Lato Bold'), local('Lato-Bold'), url(https://fonts.gstatic.com/s/lato/v11/qdgUG4U09HnJwhYI-uK18wLUuEpTyoUstqEm5AMlJo4.woff) format('woff');\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "            @font-face {\r\n"
				+ "                font-family: 'Lato';\r\n"
				+ "                font-style: italic;\r\n"
				+ "                font-weight: 400;\r\n"
				+ "                src: local('Lato Italic'), local('Lato-Italic'), url(https://fonts.gstatic.com/s/lato/v11/RYyZNoeFgb0l7W3Vu1aSWOvvDin1pK8aKteLpeZ5c0A.woff) format('woff');\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "            @font-face {\r\n"
				+ "                font-family: 'Lato';\r\n"
				+ "                font-style: italic;\r\n"
				+ "                font-weight: 700;\r\n"
				+ "                src: local('Lato Bold Italic'), local('Lato-BoldItalic'), url(https://fonts.gstatic.com/s/lato/v11/HkF_qI1x_noxlxhrhMQYELO3LdcAZYWl9Si6vvxL-qU.woff) format('woff');\r\n"
				+ "            }\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        /* CLIENT-SPECIFIC STYLES */\r\n"
				+ "        body,\r\n"
				+ "        table,\r\n"
				+ "        td,\r\n"
				+ "        a {\r\n"
				+ "            -webkit-text-size-adjust: 100%;\r\n"
				+ "            -ms-text-size-adjust: 100%;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        table,\r\n"
				+ "        td {\r\n"
				+ "            mso-table-lspace: 0pt;\r\n"
				+ "            mso-table-rspace: 0pt;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        img {\r\n"
				+ "            -ms-interpolation-mode: bicubic;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        /* RESET STYLES */\r\n"
				+ "        img {\r\n"
				+ "            border: 0;\r\n"
				+ "            height: auto;\r\n"
				+ "            line-height: 100%;\r\n"
				+ "            outline: none;\r\n"
				+ "            text-decoration: none;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        table {\r\n"
				+ "            border-collapse: collapse !important;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        body {\r\n"
				+ "            height: 100% !important;\r\n"
				+ "            margin: 0 !important;\r\n"
				+ "            padding: 0 !important;\r\n"
				+ "            width: 100% !important;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        /* iOS BLUE LINKS */\r\n"
				+ "        a[x-apple-data-detectors] {\r\n"
				+ "            color: inherit !important;\r\n"
				+ "            text-decoration: none !important;\r\n"
				+ "            font-size: inherit !important;\r\n"
				+ "            font-family: inherit !important;\r\n"
				+ "            font-weight: inherit !important;\r\n"
				+ "            line-height: inherit !important;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        /* MOBILE STYLES */\r\n"
				+ "        @media screen and (max-width:600px) {\r\n"
				+ "            h1 {\r\n"
				+ "                font-size: 32px !important;\r\n"
				+ "                line-height: 32px !important;\r\n"
				+ "            }\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        /* ANDROID CENTER FIX */\r\n"
				+ "        div[style*=\"margin: 16px 0;\"] {\r\n"
				+ "            margin: 0 !important;\r\n"
				+ "        }\r\n"
				+ "    </style>\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body style=\"background-color: #f4f4f4; margin: 0 !important; padding: 0 !important;\">\r\n"
				+ "    <!-- HIDDEN PREHEADER TEXT -->\r\n"
				+ "    <div style=\"display: none; font-size: 1px; color: #fefefe; line-height: 1px; font-family: 'Lato', Helvetica, Arial, sans-serif; max-height: 0px; max-width: 0px; opacity: 0; overflow: hidden;\"> We're thrilled to have you here! Get ready to dive into your new account.\r\n"
				+ "    </div>\r\n"
				+ "    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
				+ "        <!-- LOGO -->\r\n"
				+ "        <tr>\r\n"
				+ "            <td bgcolor=\"#FFA73B\" align=\"center\">\r\n"
				+ "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"max-width: 600px;\">\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td align=\"center\" valign=\"top\" style=\"padding: 40px 10px 40px 10px;\"> </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                </table>\r\n"
				+ "            </td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td bgcolor=\"#FFA73B\" align=\"center\" style=\"padding: 0px 10px 0px 10px;\">\r\n"
				+ "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"max-width: 600px;\">\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td bgcolor=\"#ffffff\" align=\"center\" valign=\"top\" style=\"padding: 40px 20px 20px 20px; border-radius: 4px 4px 0px 0px; color: #111111; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 48px; font-weight: 400; letter-spacing: 4px; line-height: 48px;\">\r\n"
				+ "                            <h1 style=\"font-size: 48px; font-weight: 400; margin: 2;\">Welcome!</h1> <img src=\" https://img.icons8.com/clouds/100/000000/handshake.png\" width=\"125\" height=\"120\" style=\"display: block; border: 0px;\" />\r\n"
				+ "                        </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                </table>\r\n"
				+ "            </td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td bgcolor=\"#f4f4f4\" align=\"center\" style=\"padding: 0px 10px 0px 10px;\">\r\n"
				+ "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"max-width: 600px;\">\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td bgcolor=\"#ffffff\" align=\"left\" style=\"padding: 20px 30px 40px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;\">\r\n"
				+ "                            <p style=\"margin: 0;\">We're excited to have you get started. First, you need to confirm your account. Just press the button below.</p>\r\n"
				+ "                        </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td bgcolor=\"#ffffff\" align=\"left\">\r\n"
				+ "                            <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
				+ "                                <tr>\r\n"
				+ "                                    <td bgcolor=\"#ffffff\" align=\"center\" style=\"padding: 20px 30px 60px 30px;\">\r\n"
				+ "                                        <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
				+ "                                            <tr>\r\n"
				+ "                                                <td align=\"center\" style=\"border-radius: 3px;\" bgcolor=\"#FFA73B\"><a href=\"#\" target=\"_blank\" style=\"font-size: 20px; font-family: Helvetica, Arial, sans-serif; color: #ffffff; text-decoration: none; color: #ffffff; text-decoration: none; padding: 15px 25px; border-radius: 2px; border: 1px solid #FFA73B; display: inline-block;\">"+otp+"</a></td>\r\n"
				+ "                                            </tr>\r\n"
				+ "                                        </table>\r\n"
				+ "                                    </td>\r\n"
				+ "                                </tr>\r\n"
				+ "                            </table>\r\n"
				+ "                        </td>\r\n"
				+ "                    </tr> <!-- COPY -->\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td bgcolor=\"#ffffff\" align=\"left\" style=\"padding: 0px 30px 0px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;\">\r\n"
				+ "                            <p style=\"margin: 0;\">If that doesn't work, copy and paste the following link in your browser:</p>\r\n"
				+ "                        </td>\r\n"
				+ "                    </tr> <!-- COPY -->\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td bgcolor=\"#ffffff\" align=\"left\" style=\"padding: 20px 30px 20px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;\">\r\n"
				+ "                            <p style=\"margin: 0;\"><a href=\"#\" target=\"_blank\" style=\"color: #FFA73B;\">https://bit.li.utlddssdstueincx</a></p>\r\n"
				+ "                        </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td bgcolor=\"#ffffff\" align=\"left\" style=\"padding: 0px 30px 20px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;\">\r\n"
				+ "                            <p style=\"margin: 0;\">If you have any questions, just reply to this email&mdash;we're always happy to help out.</p>\r\n"
				+ "                        </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td bgcolor=\"#ffffff\" align=\"left\" style=\"padding: 0px 30px 40px 30px; border-radius: 0px 0px 4px 4px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;\">\r\n"
				+ "                            <p style=\"margin: 0;\">Cheers,<br>BBB Team</p>\r\n"
				+ "                        </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                </table>\r\n"
				+ "            </td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td bgcolor=\"#f4f4f4\" align=\"center\" style=\"padding: 30px 10px 0px 10px;\">\r\n"
				+ "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"max-width: 600px;\">\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td bgcolor=\"#FFECD1\" align=\"center\" style=\"padding: 30px 30px 30px 30px; border-radius: 4px 4px 4px 4px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;\">\r\n"
				+ "                            <h2 style=\"font-size: 20px; font-weight: 400; color: #111111; margin: 0;\">Need more help?</h2>\r\n"
				+ "                            <p style=\"margin: 0;\"><a href=\"#\" target=\"_blank\" style=\"color: #FFA73B;\">We&rsquo;re here to help you out</a></p>\r\n"
				+ "                        </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                </table>\r\n"
				+ "            </td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td bgcolor=\"#f4f4f4\" align=\"center\" style=\"padding: 0px 10px 0px 10px;\">\r\n"
				+ "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"max-width: 600px;\">\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td bgcolor=\"#f4f4f4\" align=\"left\" style=\"padding: 0px 30px 30px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; line-height: 18px;\"> <br>\r\n"
				+ "                            <p style=\"margin: 0;\">If these emails get annoying, please feel free to <a href=\"#\" target=\"_blank\" style=\"color: #111111; font-weight: 700;\">unsubscribe</a>.</p>\r\n"
				+ "                        </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                </table>\r\n"
				+ "            </td>\r\n"
				+ "        </tr>\r\n"
				+ "    </table>\r\n"
				+ "</body>\r\n"
				+ "\r\n"
				+ "</html>";
		try {
			emailOtpService.sendMail(Head, email, mailContentOtp);
		} catch (UnsupportedEncodingException | MessagingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		}
		
		public void AfterRegisterUser(String email,String Username) {
//			System.out.println(email+"$$$$$$$$$$"+Username);
			String Head ="Registration Successful: Welcome to [VotingBhart] Account is Ready ✨";
			String mailContentOtp ="<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
					+ "<html dir=\"ltr\" xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\r\n"
					+ "\r\n"
					+ "<head>\r\n"
					+ "    <meta charset=\"UTF-8\">\r\n"
					+ "    <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\">\r\n"
					+ "    <meta name=\"x-apple-disable-message-reformatting\">\r\n"
					+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
					+ "    <meta content=\"telephone=no\" name=\"format-detection\">\r\n"
					+ "    <title></title>\r\n"
					+ "    <!--[if (mso 16)]>\r\n"
					+ "    <style type=\"text/css\">\r\n"
					+ "    a {text-decoration: none;}\r\n"
					+ "    </style>\r\n"
					+ "    <![endif]-->\r\n"
					+ "    <!--[if gte mso 9]><style>sup { font-size: 100% !important; }</style><![endif]-->\r\n"
					+ "    <!--[if gte mso 9]>\r\n"
					+ "<xml>\r\n"
					+ "    <o:OfficeDocumentSettings>\r\n"
					+ "    <o:AllowPNG></o:AllowPNG>\r\n"
					+ "    <o:PixelsPerInch>96</o:PixelsPerInch>\r\n"
					+ "    </o:OfficeDocumentSettings>\r\n"
					+ "</xml>\r\n"
					+ "<![endif]-->\r\n"
					+ "    <!--[if !mso]><!-- -->\r\n"
					+ "    <link href=\"https://fonts.googleapis.com/css2?family=Imprima&display=swap\" rel=\"stylesheet\">\r\n"
					+ "    <!--<![endif]-->\r\n"
					+ "</head>\r\n"
					+ "\r\n"
					+ "<body>\r\n"
					+ "    <div dir=\"ltr\" class=\"es-wrapper-color\">\r\n"
					+ "        <!--[if gte mso 9]>\r\n"
					+ "			<v:background xmlns:v=\"urn:schemas-microsoft-com:vml\" fill=\"t\">\r\n"
					+ "				<v:fill type=\"tile\" color=\"#ffffff\"></v:fill>\r\n"
					+ "			</v:background>\r\n"
					+ "		<![endif]-->\r\n"
					+ "        <table class=\"es-wrapper\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
					+ "            <tbody>\r\n"
					+ "                <tr>\r\n"
					+ "                    <td class=\"esd-email-paddings\" valign=\"top\">\r\n"
					+ "                        <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-footer esd-header-popover\" align=\"center\">\r\n"
					+ "                            <tbody>\r\n"
					+ "                                <tr>\r\n"
					+ "                                    <td class=\"esd-stripe\" align=\"center\">\r\n"
					+ "                                        <table bgcolor=\"#bcb8b1\" class=\"es-footer-body\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\">\r\n"
					+ "                                            <tbody>\r\n"
					+ "                                                <tr>\r\n"
					+ "                                                    <td class=\"esd-structure es-p20t es-p20b es-p40r es-p40l\" align=\"left\">\r\n"
					+ "                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                            <tbody>\r\n"
					+ "                                                                <tr>\r\n"
					+ "                                                                    <td width=\"520\" class=\"esd-container-frame\" align=\"center\" valign=\"top\">\r\n"
					+ "                                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                                            <tbody>\r\n"
					+ "                                                                                <tr>\r\n"
					+ "                                                                                    <td align=\"center\" class=\"esd-block-image\" style=\"font-size: 0px;\"><a target=\"_blank\" href=\"https://viewstripo.email\"><img src=\"https://fcnwmia.stripocdn.email/content/guids/CABINET_055ba03e85e991c70304fecd78a2dceaf6b3f0bc1b0eb49336463d3599679494/images/vector.png\" alt=\"Logo\" style=\"display: block;\" height=\"60\" title=\"Logo\"></a></td>\r\n"
					+ "                                                                                </tr>\r\n"
					+ "                                                                            </tbody>\r\n"
					+ "                                                                        </table>\r\n"
					+ "                                                                    </td>\r\n"
					+ "                                                                </tr>\r\n"
					+ "                                                            </tbody>\r\n"
					+ "                                                        </table>\r\n"
					+ "                                                    </td>\r\n"
					+ "                                                </tr>\r\n"
					+ "                                            </tbody>\r\n"
					+ "                                        </table>\r\n"
					+ "                                    </td>\r\n"
					+ "                                </tr>\r\n"
					+ "                            </tbody>\r\n"
					+ "                        </table>\r\n"
					+ "                        <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-content\" align=\"center\">\r\n"
					+ "                            <tbody>\r\n"
					+ "                                <tr>\r\n"
					+ "                                    <td class=\"esd-stripe\" align=\"center\">\r\n"
					+ "                                        <table bgcolor=\"#efefef\" class=\"es-content-body\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" style=\"border-radius: 20px 20px 0 0 \">\r\n"
					+ "                                            <tbody>\r\n"
					+ "                                                <tr>\r\n"
					+ "                                                    <td class=\"esd-structure es-p40t es-p40r es-p40l\" align=\"left\">\r\n"
					+ "                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                            <tbody>\r\n"
					+ "                                                                <tr>\r\n"
					+ "                                                                    <td width=\"520\" class=\"esd-container-frame\" align=\"center\" valign=\"top\">\r\n"
					+ "                                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                                            <tbody>\r\n"
					+ "                                                                                <tr>\r\n"
					+ "                                                                                    <td align=\"left\" class=\"esd-block-image\" style=\"font-size: 0px;\"><a target=\"_blank\" href=\"https://viewstripo.email\"><img src=\"https://fcnwmia.stripocdn.email/content/guids/CABINET_ee77850a5a9f3068d9355050e69c76d26d58c3ea2927fa145f0d7a894e624758/images/group_4076323.png\" alt=\"Confirm email\" style=\"display: block; border-radius: 100px;\" width=\"100\" title=\"Confirm email\" class=\"adapt-img\"></a></td>\r\n"
					+ "                                                                                </tr>\r\n"
					+ "                                                                            </tbody>\r\n"
					+ "                                                                        </table>\r\n"
					+ "                                                                    </td>\r\n"
					+ "                                                                </tr>\r\n"
					+ "                                                            </tbody>\r\n"
					+ "                                                        </table>\r\n"
					+ "                                                    </td>\r\n"
					+ "                                                </tr>\r\n"
					+ "                                                <tr>\r\n"
					+ "                                                    <td class=\"es-p20t es-p40r es-p40l esd-structure\" align=\"left\">\r\n"
					+ "                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                            <tbody>\r\n"
					+ "                                                                <tr>\r\n"
					+ "                                                                    <td width=\"520\" class=\"esd-container-frame\" align=\"center\" valign=\"top\">\r\n"
					+ "                                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" bgcolor=\"#fafafa\" style=\"background-color: #fafafa; border-radius: 10px; border-collapse: separate;\">\r\n"
					+ "                                                                            <tbody>\r\n"
					+ "                                                                                <tr>\r\n"
					+ "                                                                                    <td align=\"left\" class=\"esd-block-text es-p20\">\r\n"
					+ "                                                                                        <h3>Welcome, "+Username+"</h3>\r\n"
					+ "                                                                                        <p><br></p>\r\n"
					+ "                                                                                        <p>Congratulations on completing your registration with [VotingBhart] ! 🎉</p>\r\n"
					+ "                                                                                        <p><br></p>\r\n"
					+ "                                                                                        <p>You're now part of our community, and we're thrilled to have you on board. Get ready to explore, connect, and [state the main benefit or purpose of your platform].<br></p>\r\n"
					+ "                                                                                        <p><br></p>\r\n"
					+ "                                                                                        <p>Should you have any questions or need assistance, feel free to reach out to our friendly support team. We're here to help you make the most of your [Your Platform Name] experience.<br></p>\r\n"
					+ "                                                                                        <p><br></p>\r\n"
					+ "                                                                                        <p>Should you have any questions or need assistance, feel free to reach out to our friendly support team. We're here to help you make the most of your [Your Platform Name] experience.<br></p>\r\n"
					+ "                                                                                        <p><br></p>\r\n"
					+ "                                                                                        <p>Best regards,&nbsp;<br></p>\r\n"
					+ "                                                                                        <p>The [VotingBhart] Team<br></p>\r\n"
					+ "                                                                                    </td>\r\n"
					+ "                                                                                </tr>\r\n"
					+ "                                                                            </tbody>\r\n"
					+ "                                                                        </table>\r\n"
					+ "                                                                    </td>\r\n"
					+ "                                                                </tr>\r\n"
					+ "                                                            </tbody>\r\n"
					+ "                                                        </table>\r\n"
					+ "                                                    </td>\r\n"
					+ "                                                </tr>\r\n"
					+ "                                            </tbody>\r\n"
					+ "                                        </table>\r\n"
					+ "                                    </td>\r\n"
					+ "                                </tr>\r\n"
					+ "                            </tbody>\r\n"
					+ "                        </table>\r\n"
					+ "                        <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-content\" align=\"center\">\r\n"
					+ "                            <tbody>\r\n"
					+ "                                <tr>\r\n"
					+ "                                    <td class=\"esd-stripe\" align=\"center\">\r\n"
					+ "                                        <table bgcolor=\"#efefef\" class=\"es-content-body\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\">\r\n"
					+ "                                            <tbody>\r\n"
					+ "                                                <tr>\r\n"
					+ "                                                    <td class=\"esd-structure es-p40r es-p40l\" align=\"left\">\r\n"
					+ "                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                            <tbody>\r\n"
					+ "                                                                <tr>\r\n"
					+ "                                                                    <td width=\"520\" class=\"esd-container-frame\" align=\"center\" valign=\"top\">\r\n"
					+ "                                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                                            <tbody>\r\n"
					+ "                                                                                <tr>\r\n"
					+ "                                                                                    <td align=\"center\" class=\"esd-block-spacer es-p40t es-p20b\" style=\"font-size:0\">\r\n"
					+ "                                                                                        <table border=\"0\" width=\"100%\" height=\"100%\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
					+ "                                                                                            <tbody>\r\n"
					+ "                                                                                                <tr>\r\n"
					+ "                                                                                                    <td style=\"border-bottom: 1px solid #666666; background: unset; height: 1px; width: 100%; margin: 0px;\"></td>\r\n"
					+ "                                                                                                </tr>\r\n"
					+ "                                                                                            </tbody>\r\n"
					+ "                                                                                        </table>\r\n"
					+ "                                                                                    </td>\r\n"
					+ "                                                                                </tr>\r\n"
					+ "                                                                            </tbody>\r\n"
					+ "                                                                        </table>\r\n"
					+ "                                                                    </td>\r\n"
					+ "                                                                </tr>\r\n"
					+ "                                                            </tbody>\r\n"
					+ "                                                        </table>\r\n"
					+ "                                                    </td>\r\n"
					+ "                                                </tr>\r\n"
					+ "                                            </tbody>\r\n"
					+ "                                        </table>\r\n"
					+ "                                    </td>\r\n"
					+ "                                </tr>\r\n"
					+ "                            </tbody>\r\n"
					+ "                        </table>\r\n"
					+ "                        <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-content\" align=\"center\">\r\n"
					+ "                            <tbody>\r\n"
					+ "                                <tr>\r\n"
					+ "                                    <td class=\"esd-stripe\" align=\"center\">\r\n"
					+ "                                        <table bgcolor=\"#efefef\" class=\"es-content-body\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" style=\"border-radius: 0 0 20px 20px\">\r\n"
					+ "                                            <tbody>\r\n"
					+ "                                                <tr>\r\n"
					+ "                                                    <td class=\"esd-structure es-p20t es-p20b es-p40r es-p40l esdev-adapt-off\" align=\"left\">\r\n"
					+ "                                                        <table width=\"520\" cellpadding=\"0\" cellspacing=\"0\" class=\"esdev-mso-table\">\r\n"
					+ "                                                            <tbody>\r\n"
					+ "                                                                <tr>\r\n"
					+ "                                                                    <td class=\"esdev-mso-td\" valign=\"top\">\r\n"
					+ "                                                                        <table cellpadding=\"0\" cellspacing=\"0\" align=\"left\" class=\"es-left\">\r\n"
					+ "                                                                            <tbody>\r\n"
					+ "                                                                                <tr>\r\n"
					+ "                                                                                    <td width=\"47\" class=\"esd-container-frame\" align=\"center\" valign=\"top\">\r\n"
					+ "                                                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                                                            <tbody>\r\n"
					+ "                                                                                                <tr>\r\n"
					+ "                                                                                                    <td align=\"center\" class=\"esd-block-image es-m-txt-l\" style=\"font-size: 0px;\"><a target=\"_blank\" href=\"https://viewstripo.email\"><img src=\"https://fcnwmia.stripocdn.email/content/guids/CABINET_ee77850a5a9f3068d9355050e69c76d26d58c3ea2927fa145f0d7a894e624758/images/group_4076325.png\" alt=\"Demo\" style=\"display: block;\" width=\"47\" title=\"Demo\"></a></td>\r\n"
					+ "                                                                                                </tr>\r\n"
					+ "                                                                                            </tbody>\r\n"
					+ "                                                                                        </table>\r\n"
					+ "                                                                                    </td>\r\n"
					+ "                                                                                </tr>\r\n"
					+ "                                                                            </tbody>\r\n"
					+ "                                                                        </table>\r\n"
					+ "                                                                    </td>\r\n"
					+ "                                                                    <td width=\"20\"></td>\r\n"
					+ "                                                                    <td class=\"esdev-mso-td\" valign=\"top\">\r\n"
					+ "                                                                        <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-right\" align=\"right\">\r\n"
					+ "                                                                            <tbody>\r\n"
					+ "                                                                                <tr>\r\n"
					+ "                                                                                    <td width=\"453\" class=\"esd-container-frame\" align=\"center\" valign=\"top\">\r\n"
					+ "                                                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                                                            <tbody>\r\n"
					+ "                                                                                                <tr>\r\n"
					+ "                                                                                                    <td align=\"left\" class=\"esd-block-text\">\r\n"
					+ "                                                                                                        <p style=\"font-size: 16px;\">\"Our website's customer support team is here for you 24/7.\"<a target=\"_blank\" style=\"font-size: 16px;\" href=\"https://viewstripo.email\"></a></p>\r\n"
					+ "                                                                                                    </td>\r\n"
					+ "                                                                                                </tr>\r\n"
					+ "                                                                                            </tbody>\r\n"
					+ "                                                                                        </table>\r\n"
					+ "                                                                                    </td>\r\n"
					+ "                                                                                </tr>\r\n"
					+ "                                                                            </tbody>\r\n"
					+ "                                                                        </table>\r\n"
					+ "                                                                    </td>\r\n"
					+ "                                                                </tr>\r\n"
					+ "                                                            </tbody>\r\n"
					+ "                                                        </table>\r\n"
					+ "                                                    </td>\r\n"
					+ "                                                </tr>\r\n"
					+ "                                            </tbody>\r\n"
					+ "                                        </table>\r\n"
					+ "                                    </td>\r\n"
					+ "                                </tr>\r\n"
					+ "                            </tbody>\r\n"
					+ "                        </table>\r\n"
					+ "                        <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-footer\" align=\"center\">\r\n"
					+ "                            <tbody>\r\n"
					+ "                                <tr>\r\n"
					+ "                                    <td class=\"esd-stripe\" align=\"center\">\r\n"
					+ "                                        <table bgcolor=\"#bcb8b1\" class=\"es-footer-body\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\">\r\n"
					+ "                                            <tbody>\r\n"
					+ "                                                <tr>\r\n"
					+ "                                                    <td class=\"esd-structure es-p40t es-p30b es-p20r es-p20l\" align=\"left\" esd-custom-block-id=\"853188\">\r\n"
					+ "                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                            <tbody>\r\n"
					+ "                                                                <tr>\r\n"
					+ "                                                                    <td width=\"560\" align=\"left\" class=\"esd-container-frame\">\r\n"
					+ "                                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                                            <tbody>\r\n"
					+ "                                                                                <tr>\r\n"
					+ "                                                                                    <td align=\"center\" class=\"esd-block-social es-m-txt-c es-p10t es-p20b\" style=\"font-size:0\">\r\n"
					+ "                                                                                        <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-table-not-adapt es-social\">\r\n"
					+ "                                                                                            <tbody>\r\n"
					+ "                                                                                                <tr>\r\n"
					+ "                                                                                                    <td align=\"center\" valign=\"top\" esd-tmp-icon-type=\"twitter\" class=\"es-p5r\"><a target=\"_blank\" href><img src=\"https://fcnwmia.stripocdn.email/content/assets/img/social-icons/logo-black/twitter-logo-black.png\" alt=\"Tw\" title=\"Twitter\" height=\"24\"></a></td>\r\n"
					+ "                                                                                                    <td align=\"center\" valign=\"top\" esd-tmp-icon-type=\"facebook\" class=\"es-p5r\"><a target=\"_blank\" href><img src=\"https://fcnwmia.stripocdn.email/content/assets/img/social-icons/logo-black/facebook-logo-black.png\" alt=\"Fb\" title=\"Facebook\" height=\"24\"></a></td>\r\n"
					+ "                                                                                                    <td align=\"center\" valign=\"top\" esd-tmp-icon-type=\"linkedin\"><a target=\"_blank\" href><img src=\"https://fcnwmia.stripocdn.email/content/assets/img/social-icons/logo-black/linkedin-logo-black.png\" alt=\"In\" title=\"Linkedin\" height=\"24\"></a></td>\r\n"
					+ "                                                                                                </tr>\r\n"
					+ "                                                                                            </tbody>\r\n"
					+ "                                                                                        </table>\r\n"
					+ "                                                                                    </td>\r\n"
					+ "                                                                                </tr>\r\n"
					+ "                                                                                <tr>\r\n"
					+ "                                                                                    <td align=\"center\" class=\"esd-block-text\" esd-links-underline=\"none\">\r\n"
					+ "                                                                                        <p style=\"font-size: 13px;\"><a target=\"_blank\" style=\"text-decoration: none;\"></a><a target=\"_blank\" style=\"text-decoration: none;\">Privacy Policy</a><a target=\"_blank\" style=\"font-size: 13px; text-decoration: none;\"></a> • <a target=\"_blank\" style=\"text-decoration: none;\">Unsubscribe</a></p>\r\n"
					+ "                                                                                    </td>\r\n"
					+ "                                                                                </tr>\r\n"
					+ "                                                                                <tr>\r\n"
					+ "                                                                                    <td align=\"center\" class=\"esd-block-text es-p20t\" esd-links-underline=\"none\">\r\n"
					+ "                                                                                        <p><a target=\"_blank\"></a>Copyright © 2023 VotingBhart<a target=\"_blank\"></a></p>\r\n"
					+ "                                                                                    </td>\r\n"
					+ "                                                                                </tr>\r\n"
					+ "                                                                            </tbody>\r\n"
					+ "                                                                        </table>\r\n"
					+ "                                                                    </td>\r\n"
					+ "                                                                </tr>\r\n"
					+ "                                                            </tbody>\r\n"
					+ "                                                        </table>\r\n"
					+ "                                                    </td>\r\n"
					+ "                                                </tr>\r\n"
					+ "                                                <tr>\r\n"
					+ "                                                    <td class=\"esd-structure es-p40t es-p30b es-p20r es-p20l\" align=\"left\" esd-custom-block-id=\"853188\">\r\n"
					+ "                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                            <tbody>\r\n"
					+ "                                                                <tr>\r\n"
					+ "                                                                    <td width=\"560\" align=\"left\" class=\"esd-container-frame\">\r\n"
					+ "                                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                                            <tbody>\r\n"
					+ "                                                                                <tr>\r\n"
					+ "                                                                                    <td align=\"center\" class=\"esd-empty-container\" style=\"display: none;\"></td>\r\n"
					+ "                                                                                </tr>\r\n"
					+ "                                                                            </tbody>\r\n"
					+ "                                                                        </table>\r\n"
					+ "                                                                    </td>\r\n"
					+ "                                                                </tr>\r\n"
					+ "                                                            </tbody>\r\n"
					+ "                                                        </table>\r\n"
					+ "                                                    </td>\r\n"
					+ "                                                </tr>\r\n"
					+ "                                            </tbody>\r\n"
					+ "                                        </table>\r\n"
					+ "                                    </td>\r\n"
					+ "                                </tr>\r\n"
					+ "                            </tbody>\r\n"
					+ "                        </table>\r\n"
					+ "                        <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-footer esd-footer-popover\" align=\"center\">\r\n"
					+ "                            <tbody>\r\n"
					+ "                                <tr>\r\n"
					+ "                                    <td class=\"esd-stripe\" align=\"center\" esd-custom-block-id=\"819294\">\r\n"
					+ "                                        <table bgcolor=\"#ffffff\" class=\"es-footer-body\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\">\r\n"
					+ "                                            <tbody>\r\n"
					+ "                                                <tr>\r\n"
					+ "                                                    <td class=\"esd-structure es-p20\" align=\"left\">\r\n"
					+ "                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                            <tbody>\r\n"
					+ "                                                                <tr>\r\n"
					+ "                                                                    <td width=\"560\" class=\"esd-container-frame\" align=\"left\">\r\n"
					+ "                                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "                                                                            <tbody>\r\n"
					+ "                                                                                <tr>\r\n"
					+ "                                                                                    <td align=\"center\" class=\"esd-empty-container\" style=\"display: none;\"></td>\r\n"
					+ "                                                                                </tr>\r\n"
					+ "                                                                            </tbody>\r\n"
					+ "                                                                        </table>\r\n"
					+ "                                                                    </td>\r\n"
					+ "                                                                </tr>\r\n"
					+ "                                                            </tbody>\r\n"
					+ "                                                        </table>\r\n"
					+ "                                                    </td>\r\n"
					+ "                                                </tr>\r\n"
					+ "                                            </tbody>\r\n"
					+ "                                        </table>\r\n"
					+ "                                    </td>\r\n"
					+ "                                </tr>\r\n"
					+ "                            </tbody>\r\n"
					+ "                        </table>\r\n"
					+ "                    </td>\r\n"
					+ "                </tr>\r\n"
					+ "            </tbody>\r\n"
					+ "        </table>\r\n"
					+ "    </div>\r\n"
					+ "</body>\r\n"
					+ "\r\n"
					+ "</html>";
			
			try {
				emailOtpService.afterRegisterEmail(Head, email, mailContentOtp);
			} catch (UnsupportedEncodingException | MessagingException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
	}
		
		public void updatePasswordConfimEmail(String Username ,String Email) throws UnsupportedEncodingException, MessagingException {
			String Head ="Forget Password Successfully";
			String mailContentOtp ="<!DOCTYPE HTML PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional //EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n"
					+ "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\n"
					+ "<head>\n"
					+ "<!--[if gte mso 9]>\n"
					+ "<xml>\n"
					+ "  <o:OfficeDocumentSettings>\n"
					+ "    <o:AllowPNG/>\n"
					+ "    <o:PixelsPerInch>96</o:PixelsPerInch>\n"
					+ "  </o:OfficeDocumentSettings>\n"
					+ "</xml>\n"
					+ "<![endif]-->\n"
					+ "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n"
					+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
					+ "  <meta name=\"x-apple-disable-message-reformatting\">\n"
					+ "  <!--[if !mso]><!--><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><!--<![endif]-->\n"
					+ "  <title></title>\n"
					+ "  \n"
					+ "    <style type=\"text/css\">\n"
					+ "      @media only screen and (min-width: 620px) {\n"
					+ "  .u-row {\n"
					+ "    width: 600px !important;\n"
					+ "  }\n"
					+ "  .u-row .u-col {\n"
					+ "    vertical-align: top;\n"
					+ "  }\n"
					+ "\n"
					+ "  .u-row .u-col-33p33 {\n"
					+ "    width: 199.98px !important;\n"
					+ "  }\n"
					+ "\n"
					+ "  .u-row .u-col-66p67 {\n"
					+ "    width: 400.02px !important;\n"
					+ "  }\n"
					+ "\n"
					+ "  .u-row .u-col-100 {\n"
					+ "    width: 600px !important;\n"
					+ "  }\n"
					+ "\n"
					+ "}\n"
					+ "\n"
					+ "@media (max-width: 620px) {\n"
					+ "  .u-row-container {\n"
					+ "    max-width: 100% !important;\n"
					+ "    padding-left: 0px !important;\n"
					+ "    padding-right: 0px !important;\n"
					+ "  }\n"
					+ "  .u-row .u-col {\n"
					+ "    min-width: 320px !important;\n"
					+ "    max-width: 100% !important;\n"
					+ "    display: block !important;\n"
					+ "  }\n"
					+ "  .u-row {\n"
					+ "    width: 100% !important;\n"
					+ "  }\n"
					+ "  .u-col {\n"
					+ "    width: 100% !important;\n"
					+ "  }\n"
					+ "  .u-col > div {\n"
					+ "    margin: 0 auto;\n"
					+ "  }\n"
					+ "}\n"
					+ "body {\n"
					+ "  margin: 0;\n"
					+ "  padding: 0;\n"
					+ "}\n"
					+ "\n"
					+ "table,\n"
					+ "tr,\n"
					+ "td {\n"
					+ "  vertical-align: top;\n"
					+ "  border-collapse: collapse;\n"
					+ "}\n"
					+ "\n"
					+ "p {\n"
					+ "  margin: 0;\n"
					+ "}\n"
					+ "\n"
					+ ".ie-container table,\n"
					+ ".mso-container table {\n"
					+ "  table-layout: fixed;\n"
					+ "}\n"
					+ "\n"
					+ "* {\n"
					+ "  line-height: inherit;\n"
					+ "}\n"
					+ "\n"
					+ "a[x-apple-data-detectors='true'] {\n"
					+ "  color: inherit !important;\n"
					+ "  text-decoration: none !important;\n"
					+ "}\n"
					+ "\n"
					+ "table, td { color: #000000; } #u_body a { color: #0000ee; text-decoration: underline; } @media (max-width: 480px) { #u_content_image_1 .v-container-padding-padding { padding: 40px 0px 0px !important; } #u_content_image_1 .v-src-width { width: auto !important; } #u_content_image_1 .v-src-max-width { max-width: 55% !important; } #u_content_heading_3 .v-font-size { font-size: 18px !important; } #u_content_heading_2 .v-container-padding-padding { padding: 5px 10px 40px !important; } #u_content_heading_4 .v-container-padding-padding { padding: 40px 10px 0px !important; } #u_content_heading_4 .v-text-align { text-align: center !important; } #u_content_divider_1 .v-container-padding-padding { padding: 10px 10px 10px 125px !important; } #u_content_text_2 .v-container-padding-padding { padding: 10px 10px 40px !important; } #u_content_text_2 .v-text-align { text-align: center !important; } #u_content_button_1 .v-size-width { width: 60% !important; } #u_content_image_4 .v-container-padding-padding { padding: 40px 10px 10px !important; } #u_content_image_4 .v-src-width { width: auto !important; } #u_content_image_4 .v-src-max-width { max-width: 30% !important; } #u_content_heading_7 .v-container-padding-padding { padding: 10px 10px 0px !important; } #u_content_heading_7 .v-text-align { text-align: center !important; } #u_content_text_5 .v-container-padding-padding { padding: 5px 10px 40px !important; } #u_content_text_5 .v-text-align { text-align: center !important; } #u_row_4.v-row-padding--vertical { padding-top: 0px !important; padding-bottom: 0px !important; } #u_content_image_2 .v-container-padding-padding { padding: 40px 10px 10px !important; } #u_content_image_2 .v-src-width { width: auto !important; } #u_content_image_2 .v-src-max-width { max-width: 30% !important; } #u_content_heading_1 .v-container-padding-padding { padding: 10px 10px 0px !important; } #u_content_heading_1 .v-text-align { text-align: center !important; } #u_content_text_1 .v-container-padding-padding { padding: 5px 10px 40px !important; } #u_content_text_1 .v-text-align { text-align: center !important; } #u_content_social_1 .v-container-padding-padding { padding: 30px 10px 10px !important; } #u_content_text_deprecated_1 .v-container-padding-padding { padding: 10px 10px 20px !important; } #u_content_image_5 .v-container-padding-padding { padding: 20px 10px 30px !important; } }\n"
					+ "    </style>\n"
					+ "  \n"
					+ "  \n"
					+ "\n"
					+ "<!--[if !mso]><!--><link href=\"https://fonts.googleapis.com/css?family=Raleway:400,700&display=swap\" rel=\"stylesheet\" type=\"text/css\"><!--<![endif]-->\n"
					+ "\n"
					+ "</head>\n"
					+ "\n"
					+ "<body class=\"clean-body u_body\" style=\"margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #ffffff;color: #000000\">\n"
					+ "  <!--[if IE]><div class=\"ie-container\"><![endif]-->\n"
					+ "  <!--[if mso]><div class=\"mso-container\"><![endif]-->\n"
					+ "  <table id=\"u_body\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #ffffff;width:100%\" cellpadding=\"0\" cellspacing=\"0\">\n"
					+ "  <tbody>\n"
					+ "  <tr style=\"vertical-align: top\">\n"
					+ "    <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\n"
					+ "    <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td align=\"center\" style=\"background-color: #ffffff;\"><![endif]-->\n"
					+ "    \n"
					+ "  \n"
					+ "  \n"
					+ "<div class=\"u-row-container v-row-padding--vertical\" style=\"padding: 0px;background-color: #ffffff\">\n"
					+ "  <div class=\"u-row\" style=\"margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\">\n"
					+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\n"
					+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: #ffffff;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: transparent;\"><![endif]-->\n"
					+ "      \n"
					+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"background-color: #ffffff;width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\n"
					+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
					+ "  <div style=\"background-color: #ffffff;height: 100%;width: 100% !important;\">\n"
					+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"box-sizing: border-box; height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n"
					+ "  \n"
					+ "<table id=\"u_content_image_1\" style=\"font-family:'Raleway',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
					+ "  <tbody>\n"
					+ "    <tr>\n"
					+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:50px 0px 0px;font-family:'Raleway',sans-serif;\" align=\"left\">\n"
					+ "        \n"
					+ "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n"
					+ "  <tr>\n"
					+ "    <td class=\"v-text-align\" style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\n"
					+ "      \n"
					+ "      <img align=\"center\" border=\"0\" src=\"img/image-8.gif\" alt=\"image\" title=\"image\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 30%;max-width: 180px;\" width=\"180\" class=\"v-src-width v-src-max-width\"/>\n"
					+ "      \n"
					+ "    </td>\n"
					+ "  </tr>\n"
					+ "</table>\n"
					+ "\n"
					+ "      </td>\n"
					+ "    </tr>\n"
					+ "  </tbody>\n"
					+ "</table>\n"
					+ "\n"
					+ "<table id=\"u_content_heading_3\" style=\"font-family:'Raleway',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
					+ "  <tbody>\n"
					+ "    <tr>\n"
					+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 10px 0px;font-family:'Raleway',sans-serif;\" align=\"left\">\n"
					+ "        \n"
					+ "  <!--[if mso]><table width=\"100%\"><tr><td><![endif]-->\n"
					+ "    <h1 class=\"v-text-align v-font-size\" style=\"margin: 0px; line-height: 140%; text-align: center; word-wrap: break-word; font-size: 22px; font-weight: 400;\"><strong>Your Password has been Changed</strong></h1>\n"
					+ "  <!--[if mso]></td></tr></table><![endif]-->\n"
					+ "\n"
					+ "      </td>\n"
					+ "    </tr>\n"
					+ "  </tbody>\n"
					+ "</table>\n"
					+ "\n"
					+ "<table id=\"u_content_heading_2\" style=\"font-family:'Raleway',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
					+ "  <tbody>\n"
					+ "    <tr>\n"
					+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:5px 10px 50px;font-family:'Raleway',sans-serif;\" align=\"left\">\n"
					+ "        \n"
					+ "  <!--[if mso]><table width=\"100%\"><tr><td><![endif]-->\n"
					+ "    <h1 class=\"v-text-align v-font-size\" style=\"margin: 0px; color: #5c5c5c; line-height: 140%; text-align: center; word-wrap: break-word; font-size: 14px; font-weight: 400;\">Please login to your email account again</h1>\n"
					+ "  <!--[if mso]></td></tr></table><![endif]-->\n"
					+ "\n"
					+ "      </td>\n"
					+ "    </tr>\n"
					+ "  </tbody>\n"
					+ "</table>\n"
					+ "\n"
					+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
					+ "  </div>\n"
					+ "</div>\n"
					+ "<!--[if (mso)|(IE)]></td><![endif]-->\n"
					+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
					+ "    </div>\n"
					+ "  </div>\n"
					+ "  </div>\n"
					+ "  \n"
					+ "\n"
					+ "\n"
					+ "  \n"
					+ "  \n"
					+ "<div class=\"u-row-container v-row-padding--vertical\" style=\"padding: 0px;background-color: transparent\">\n"
					+ "  <div class=\"u-row\" style=\"margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\">\n"
					+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\n"
					+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: transparent;\"><![endif]-->\n"
					+ "      \n"
					+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"background-color: #f0f5f6;width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\n"
					+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
					+ "  <div style=\"background-color: #f0f5f6;height: 100%;width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\n"
					+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"box-sizing: border-box; height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\n"
					+ "  \n"
					+ "<table id=\"u_content_heading_4\" style=\"font-family:'Raleway',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
					+ "  <tbody>\n"
					+ "    <tr>\n"
					+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:50px 60px 0px;font-family:'Raleway',sans-serif;\" align=\"left\">\n"
					+ "        \n"
					+ "  <!--[if mso]><table width=\"100%\"><tr><td><![endif]-->\n"
					+ "    <h1 class=\"v-text-align v-font-size\" style=\"margin: 0px; line-height: 140%; text-align: left; word-wrap: break-word; font-size: 20px; font-weight: 400;\"><strong>Subject: Password Change Confirmation</strong></h1>\n"
					+ "  <!--[if mso]></td></tr></table><![endif]-->\n"
					+ "\n"
					+ "      </td>\n"
					+ "    </tr>\n"
					+ "  </tbody>\n"
					+ "</table>\n"
					+ "\n"
					+ "<table id=\"u_content_divider_1\" style=\"font-family:'Raleway',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
					+ "  <tbody>\n"
					+ "    <tr>\n"
					+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 10px 10px 60px;font-family:'Raleway',sans-serif;\" align=\"left\">\n"
					+ "        \n"
					+ "  <table height=\"0px\" align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"38%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 2px solid #BBBBBB;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
					+ "    <tbody>\n"
					+ "      <tr style=\"vertical-align: top\">\n"
					+ "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
					+ "          <span>&#160;</span>\n"
					+ "        </td>\n"
					+ "      </tr>\n"
					+ "    </tbody>\n"
					+ "  </table>\n"
					+ "\n"
					+ "      </td>\n"
					+ "    </tr>\n"
					+ "  </tbody>\n"
					+ "</table>\n"
					+ "\n"
					+ "<table id=\"u_content_text_2\" style=\"font-family:'Raleway',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
					+ "  <tbody>\n"
					+ "    <tr>\n"
					+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 60px 50px;font-family:'Raleway',sans-serif;\" align=\"left\">\n"
					+ "        \n"
					+ "  <div class=\"v-text-align v-font-size\" style=\"font-size: 14px; line-height: 140%; text-align: justify; word-wrap: break-word;\">\n"
					+ "    <p style=\"line-height: 140%;\">Dear ["+Username+"],</p>\n"
					+ "<p style=\"line-height: 140%;\"> </p>\n"
					+ "<p style=\"line-height: 140%;\">This is to confirm that the password for your account has been successfully changed. Your account is now secured with the new password that you have set.</p>\n"
					+ "<p style=\"line-height: 140%;\"> </p>\n"
					+ "<p style=\"line-height: 140%;\">If you did not change your password, please contact us immediately to report any unauthorized access to your account.</p>\n"
					+ "<p style=\"line-height: 140%;\"> </p>\n"
					+ "<p style=\"line-height: 140%;\">If you have any issues or concerns regarding your account, please do not hesitate to contact our customer support team for further assistance.</p>\n"
					+ "<p style=\"line-height: 140%;\"> </p>\n"
					+ "<p style=\"line-height: 140%;\">Thank you for using our service.</p>\n"
					+ "<p style=\"line-height: 140%;\"> </p>\n"
					+ "<p style=\"line-height: 140%;\">Best regards,</p>\n"
					+ "<p style=\"line-height: 140%;\">[Your Name]</p>\n"
					+ "  </div>\n"
					+ "\n"
					+ "      </td>\n"
					+ "    </tr>\n"
					+ "  </tbody>\n"
					+ "</table>\n"
					+ "\n"
					+ "<table id=\"u_content_button_1\" style=\"font-family:'Raleway',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
					+ "  <tbody>\n"
					+ "    <tr>\n"
					+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Raleway',sans-serif;\" align=\"left\">\n"
					+ "        \n"
					+ "  <!--[if mso]><style>.v-button {background: transparent !important;}</style><![endif]-->\n"
					+ "<div class=\"v-text-align\" align=\"center\">\n"
					+ "  <!--[if mso]><v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" href=\"https://unlayer.com/templates\" style=\"height:37px; v-text-anchor:middle; width:155px;\" arcsize=\"11%\"  stroke=\"f\" fillcolor=\"#316b94\"><w:anchorlock/><center style=\"color:#FFFFFF;\"><![endif]-->\n"
					+ "    <a href=\"https://unlayer.com/templates\" target=\"_blank\" class=\"v-button v-size-width v-font-size\" style=\"box-sizing: border-box;display: inline-block;text-decoration: none;-webkit-text-size-adjust: none;text-align: center;color: #FFFFFF; background-color: #316b94; border-radius: 4px;-webkit-border-radius: 4px; -moz-border-radius: 4px; width:auto; max-width:100%; overflow-wrap: break-word; word-break: break-word; word-wrap:break-word; mso-border-alt: none;font-size: 14px;\">\n"
					+ "      <span style=\"display:block;padding:10px 20px;line-height:120%;\"><span style=\"line-height: 16.8px;\">Go to my Account</span></span>\n"
					+ "    </a>\n"
					+ "    <!--[if mso]></center></v:roundrect><![endif]-->\n"
					+ "</div>\n"
					+ "\n"
					+ "      </td>\n"
					+ "    </tr>\n"
					+ "  </tbody>\n"
					+ "</table>\n"
					+ "\n"
					+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
					+ "  </div>\n"
					+ "</div>\n"
					+ "<!--[if (mso)|(IE)]></td><![endif]-->\n"
					+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
					+ "    </div>\n"
					+ "  </div>\n"
					+ "  </div>\n"
					+ "  \n"
					+ "\n"
					+ "\n"
					+ "  \n"
					+ "  \n"
					+ "<div class=\"u-row-container v-row-padding--vertical\" style=\"padding: 0px;background-color: #ffffff\">\n"
					+ "  <div class=\"u-row\" style=\"margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\">\n"
					+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\n"
					+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: #ffffff;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: transparent;\"><![endif]-->\n"
					+ "      \n"
					+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"200\" style=\"background-color: #2980b9;width: 200px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\n"
					+ "<div class=\"u-col u-col-33p33\" style=\"max-width: 320px;min-width: 200px;display: table-cell;vertical-align: top;\">\n"
					+ "  <div style=\"background-color: #2980b9;height: 100%;width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\n"
					+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"box-sizing: border-box; height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\n"
					+ "  \n"
					+ "<table id=\"u_content_image_4\" style=\"font-family:'Raleway',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
					+ "  <tbody>\n"
					+ "    <tr>\n"
					+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:30px 10px;font-family:'Raleway',sans-serif;\" align=\"left\">\n"
					+ "        \n"
					+ "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n"
					+ "  <tr>\n"
					+ "    <td class=\"v-text-align\" style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\n"
					+ "      \n"
					+ "      <img align=\"center\" border=\"0\" src=\"images/image-6.png\" alt=\"image\" title=\"image\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 65%;max-width: 117px;\" width=\"117\" class=\"v-src-width v-src-max-width\"/>\n"
					+ "      \n"
					+ "    </td>\n"
					+ "  </tr>\n"
					+ "</table>\n"
					+ "\n"
					+ "      </td>\n"
					+ "    </tr>\n"
					+ "  </tbody>\n"
					+ "</table>\n"
					+ "\n"
					+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
					+ "  </div>\n"
					+ "</div>\n"
					+ "<!--[if (mso)|(IE)]></td><![endif]-->\n"
					+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"400\" style=\"background-color: #2980b9;width: 400px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\n"
					+ "<div class=\"u-col u-col-66p67\" style=\"max-width: 320px;min-width: 400px;display: table-cell;vertical-align: top;\">\n"
					+ "  <div style=\"background-color: #2980b9;height: 100%;width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\n"
					+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"box-sizing: border-box; height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\n"
					+ "  \n"
					+ "<table id=\"u_content_heading_7\" style=\"font-family:'Raleway',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
					+ "  <tbody>\n"
					+ "    <tr>\n"
					+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:47px 10px 0px;font-family:'Raleway',sans-serif;\" align=\"left\">\n"
					+ "        \n"
					+ "  <!--[if mso]><table width=\"100%\"><tr><td><![endif]-->\n"
					+ "    <h1 class=\"v-text-align v-font-size\" style=\"margin: 0px; color: #ffffff; line-height: 140%; text-align: left; word-wrap: break-word; font-size: 20px; font-weight: 400;\"><strong>How to protect your account</strong></h1>\n"
					+ "  <!--[if mso]></td></tr></table><![endif]-->\n"
					+ "\n"
					+ "      </td>\n"
					+ "    </tr>\n"
					+ "  </tbody>\n"
					+ "</table>\n"
					+ "\n"
					+ "<table id=\"u_content_text_5\" style=\"font-family:'Raleway',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
					+ "  <tbody>\n"
					+ "    <tr>\n"
					+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:5px 40px 50px 10px;font-family:'Raleway',sans-serif;\" align=\"left\">\n"
					+ "        \n"
					+ "  <div class=\"v-text-align v-font-size\" style=\"font-size: 14px; color: #ffffff; line-height: 140%; text-align: justify; word-wrap: break-word;\">\n"
					+ "    <p style=\"line-height: 140%;\">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt.</p>\n"
					+ "  </div>\n"
					+ "\n"
					+ "      </td>\n"
					+ "    </tr>\n"
					+ "  </tbody>\n"
					+ "</table>\n"
					+ "\n"
					+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
					+ "  </div>\n"
					+ "</div>\n"
					+ "<!--[if (mso)|(IE)]></td><![endif]-->\n"
					+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
					+ "    </div>\n"
					+ "  </div>\n"
					+ "  </div>\n"
					+ "  \n"
					+ "\n"
					+ "\n"
					+ "  \n"
					+ "  \n"
					+ "<div id=\"u_row_4\" class=\"u-row-container v-row-padding--vertical\" style=\"padding: 0px;background-color: transparent\">\n"
					+ "  <div class=\"u-row\" style=\"margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\">\n"
					+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\n"
					+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: transparent;\"><![endif]-->\n"
					+ "      \n"
					+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"200\" style=\"background-color: #2c3e50;width: 200px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\n"
					+ "<div class=\"u-col u-col-33p33\" style=\"max-width: 320px;min-width: 200px;display: table-cell;vertical-align: top;\">\n"
					+ "  <div style=\"background-color: #2c3e50;height: 100%;width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\n"
					+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"box-sizing: border-box; height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\n"
					+ "  \n"
					+ "<table id=\"u_content_image_2\" style=\"font-family:'Raleway',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
					+ "  <tbody>\n"
					+ "    <tr>\n"
					+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:30px 10px;font-family:'Raleway',sans-serif;\" align=\"left\">\n"
					+ "        \n"
					+ "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n"
					+ "  <tr>\n"
					+ "    <td class=\"v-text-align\" style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\n"
					+ "      \n"
					+ "      <img align=\"center\" border=\"0\" src=\"images/image-7.png\" alt=\"image\" title=\"image\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 65%;max-width: 117px;\" width=\"117\" class=\"v-src-width v-src-max-width\"/>\n"
					+ "      \n"
					+ "    </td>\n"
					+ "  </tr>\n"
					+ "</table>\n"
					+ "\n"
					+ "      </td>\n"
					+ "    </tr>\n"
					+ "  </tbody>\n"
					+ "</table>\n"
					+ "\n"
					+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
					+ "  </div>\n"
					+ "</div>\n"
					+ "<!--[if (mso)|(IE)]></td><![endif]-->\n"
					+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"400\" style=\"background-color: #2c3e50;width: 400px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\n"
					+ "<div class=\"u-col u-col-66p67\" style=\"max-width: 320px;min-width: 400px;display: table-cell;vertical-align: top;\">\n"
					+ "  <div style=\"background-color: #2c3e50;height: 100%;width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\n"
					+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"box-sizing: border-box; height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\n"
					+ "  \n"
					+ "<table id=\"u_content_heading_1\" style=\"font-family:'Raleway',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
					+ "  <tbody>\n"
					+ "    <tr>\n"
					+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:47px 10px 0px;font-family:'Raleway',sans-serif;\" align=\"left\">\n"
					+ "        \n"
					+ "  <!--[if mso]><table width=\"100%\"><tr><td><![endif]-->\n"
					+ "    <h1 class=\"v-text-align v-font-size\" style=\"margin: 0px; color: #ffffff; line-height: 140%; text-align: left; word-wrap: break-word; font-size: 20px; font-weight: 400;\"><strong>Brute-force</strong></h1>\n"
					+ "  <!--[if mso]></td></tr></table><![endif]-->\n"
					+ "\n"
					+ "      </td>\n"
					+ "    </tr>\n"
					+ "  </tbody>\n"
					+ "</table>\n"
					+ "\n"
					+ "<table id=\"u_content_text_1\" style=\"font-family:'Raleway',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
					+ "  <tbody>\n"
					+ "    <tr>\n"
					+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:5px 40px 50px 10px;font-family:'Raleway',sans-serif;\" align=\"left\">\n"
					+ "        \n"
					+ "  <div class=\"v-text-align v-font-size\" style=\"font-size: 14px; color: #ced4d9; line-height: 140%; text-align: justify; word-wrap: break-word;\">\n"
					+ "    <p style=\"line-height: 140%;\">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt.</p>\n"
					+ "  </div>\n"
					+ "\n"
					+ "      </td>\n"
					+ "    </tr>\n"
					+ "  </tbody>\n"
					+ "</table>\n"
					+ "\n"
					+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
					+ "  </div>\n"
					+ "</div>\n"
					+ "<!--[if (mso)|(IE)]></td><![endif]-->\n"
					+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
					+ "    </div>\n"
					+ "  </div>\n"
					+ "  </div>\n"
					+ "  \n"
					+ "\n"
					+ "\n"
					+ "  \n"
					+ "  \n"
					+ "<div class=\"u-row-container v-row-padding--vertical\" style=\"padding: 0px;background-color: transparent\">\n"
					+ "  <div class=\"u-row\" style=\"margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\">\n"
					+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\n"
					+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: transparent;\"><![endif]-->\n"
					+ "      \n"
					+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"background-color: #ecf0f1;width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\n"
					+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
					+ "  <div style=\"background-color: #ecf0f1;height: 100%;width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\n"
					+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"box-sizing: border-box; height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\n"
					+ "  \n"
					+ "<table id=\"u_content_social_1\" style=\"font-family:'Raleway',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
					+ "  <tbody>\n"
					+ "    <tr>\n"
					+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:50px 10px 10px;font-family:'Raleway',sans-serif;\" align=\"left\">\n"
					+ "        \n"
					+ "<div align=\"center\">\n"
					+ "  <div style=\"display: table; max-width:167px;\">\n"
					+ "  <!--[if (mso)|(IE)]><table width=\"167\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"border-collapse:collapse;\" align=\"center\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse; mso-table-lspace: 0pt;mso-table-rspace: 0pt; width:167px;\"><tr><![endif]-->\n"
					+ "  \n"
					+ "    \n"
					+ "    <!--[if (mso)|(IE)]><td width=\"32\" style=\"width:32px; padding-right: 10px;\" valign=\"top\"><![endif]-->\n"
					+ "    <table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"32\" height=\"32\" style=\"width: 32px !important;height: 32px !important;display: inline-block;border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;margin-right: 10px\">\n"
					+ "      <tbody><tr style=\"vertical-align: top\"><td align=\"left\" valign=\"middle\" style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\n"
					+ "        <a href=\"https://www.facebook.com/unlayer\" title=\"Facebook\" target=\"_blank\">\n"
					+ "          <img src=\"images/image-1.png\" alt=\"Facebook\" title=\"Facebook\" width=\"32\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;max-width: 32px !important\">\n"
					+ "        </a>\n"
					+ "      </td></tr>\n"
					+ "    </tbody></table>\n"
					+ "    <!--[if (mso)|(IE)]></td><![endif]-->\n"
					+ "    \n"
					+ "    <!--[if (mso)|(IE)]><td width=\"32\" style=\"width:32px; padding-right: 10px;\" valign=\"top\"><![endif]-->\n"
					+ "    <table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"32\" height=\"32\" style=\"width: 32px !important;height: 32px !important;display: inline-block;border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;margin-right: 10px\">\n"
					+ "      <tbody><tr style=\"vertical-align: top\"><td align=\"left\" valign=\"middle\" style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\n"
					+ "        <a href=\"https://twitter.com/unlayerapp\" title=\"Twitter\" target=\"_blank\">\n"
					+ "          <img src=\"images/image-4.png\" alt=\"Twitter\" title=\"Twitter\" width=\"32\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;max-width: 32px !important\">\n"
					+ "        </a>\n"
					+ "      </td></tr>\n"
					+ "    </tbody></table>\n"
					+ "    <!--[if (mso)|(IE)]></td><![endif]-->\n"
					+ "    \n"
					+ "    <!--[if (mso)|(IE)]><td width=\"32\" style=\"width:32px; padding-right: 10px;\" valign=\"top\"><![endif]-->\n"
					+ "    <table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"32\" height=\"32\" style=\"width: 32px !important;height: 32px !important;display: inline-block;border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;margin-right: 10px\">\n"
					+ "      <tbody><tr style=\"vertical-align: top\"><td align=\"left\" valign=\"middle\" style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\n"
					+ "        <a href=\"https://www.linkedin.com/company/unlayer/mycompany/\" title=\"LinkedIn\" target=\"_blank\">\n"
					+ "          <img src=\"images/image-3.png\" alt=\"LinkedIn\" title=\"LinkedIn\" width=\"32\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;max-width: 32px !important\">\n"
					+ "        </a>\n"
					+ "      </td></tr>\n"
					+ "    </tbody></table>\n"
					+ "    <!--[if (mso)|(IE)]></td><![endif]-->\n"
					+ "    \n"
					+ "    <!--[if (mso)|(IE)]><td width=\"32\" style=\"width:32px; padding-right: 0px;\" valign=\"top\"><![endif]-->\n"
					+ "    <table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"32\" height=\"32\" style=\"width: 32px !important;height: 32px !important;display: inline-block;border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;margin-right: 0px\">\n"
					+ "      <tbody><tr style=\"vertical-align: top\"><td align=\"left\" valign=\"middle\" style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\n"
					+ "        <a href=\"https://www.instagram.com/unlayer_official/\" title=\"Instagram\" target=\"_blank\">\n"
					+ "          <img src=\"images/image-5.png\" alt=\"Instagram\" title=\"Instagram\" width=\"32\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;max-width: 32px !important\">\n"
					+ "        </a>\n"
					+ "      </td></tr>\n"
					+ "    </tbody></table>\n"
					+ "    <!--[if (mso)|(IE)]></td><![endif]-->\n"
					+ "    \n"
					+ "    \n"
					+ "    <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
					+ "  </div>\n"
					+ "</div>\n"
					+ "\n"
					+ "      </td>\n"
					+ "    </tr>\n"
					+ "  </tbody>\n"
					+ "</table>\n"
					+ "\n"
					+ "<table id=\"u_content_text_deprecated_1\" style=\"font-family:'Raleway',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
					+ "  <tbody>\n"
					+ "    <tr>\n"
					+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 100px 30px;font-family:'Raleway',sans-serif;\" align=\"left\">\n"
					+ "        \n"
					+ "  <div class=\"v-text-align v-font-size\" style=\"font-size: 14px; line-height: 170%; text-align: center; word-wrap: break-word;\">\n"
					+ "    <p style=\"font-size: 14px; line-height: 170%;\">UNSUBSCRIBE   |   PRIVACY POLICY   |   WEB</p>\n"
					+ "<p style=\"font-size: 14px; line-height: 170%;\"> </p>\n"
					+ "<p style=\"font-size: 14px; line-height: 170%;\">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>\n"
					+ "  </div>\n"
					+ "\n"
					+ "      </td>\n"
					+ "    </tr>\n"
					+ "  </tbody>\n"
					+ "</table>\n"
					+ "\n"
					+ "<table style=\"font-family:'Raleway',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
					+ "  <tbody>\n"
					+ "    <tr>\n"
					+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:0px;font-family:'Raleway',sans-serif;\" align=\"left\">\n"
					+ "        \n"
					+ "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px solid #BBBBBB;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
					+ "    <tbody>\n"
					+ "      <tr style=\"vertical-align: top\">\n"
					+ "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
					+ "          <span>&#160;</span>\n"
					+ "        </td>\n"
					+ "      </tr>\n"
					+ "    </tbody>\n"
					+ "  </table>\n"
					+ "\n"
					+ "      </td>\n"
					+ "    </tr>\n"
					+ "  </tbody>\n"
					+ "</table>\n"
					+ "\n"
					+ "<!-- <table id=\"u_content_image_5\" style=\"font-family:'Raleway',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
					+ "  <tbody>\n"
					+ "    <tr>\n"
					+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:30px 10px;font-family:'Raleway',sans-serif;\" align=\"left\">\n"
					+ "        \n"
					+ "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n"
					+ "  <tr>\n"
					+ "    <td class=\"v-text-align\" style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\n"
					+ "      \n"
					+ "      <img align=\"center\" border=\"0\" src=\"images/image-2.png\" alt=\"image\" title=\"image\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 100%;max-width: 149px;\" width=\"149\" class=\"v-src-width v-src-max-width\"/>\n"
					+ "      \n"
					+ "    </td>\n"
					+ "  </tr>\n"
					+ "</table> \n"
					+ "\n"
					+ "      </td>\n"
					+ "    </tr>\n"
					+ "  </tbody>\n"
					+ "</table> -->\n"
					+ "\n"
					+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
					+ "  </div>\n"
					+ "</div>\n"
					+ "<!--[if (mso)|(IE)]></td><![endif]-->\n"
					+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
					+ "    </div>\n"
					+ "  </div>\n"
					+ "  </div>\n"
					+ "  \n"
					+ "\n"
					+ "\n"
					+ "    <!--[if (mso)|(IE)]></td></tr></table><![endif]-->\n"
					+ "    </td>\n"
					+ "  </tr>\n"
					+ "  </tbody>\n"
					+ "  </table>\n"
					+ "  <!--[if mso]></div><![endif]-->\n"
					+ "  <!--[if IE]></div><![endif]-->\n"
					+ "</body>\n"
					+ "\n"
					+ "</html>\n"
					+ "";
			emailOtpService.UpdatePassword(Head,Email, mailContentOtp);
		}
}
